dist: trusty
sudo: false
language: python
env:
- TOXENV=flake8
- TOXENV=isort
cache: pip
matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TOXENV=py27-1.11
  - python: 3.4
    env: TOXENV=py34-1.11
  - python: 3.4
    env: TOXENV=py34-2.0
  - python: 3.5
    env: TOXENV=py35-1.11
  - python: 3.5
    env: TOXENV=py35-2.0
  - python: 3.5
    env: TOXENV=py35-master
  - python: 3.6
    env: TOXENV=py36-1.11
  - python: 3.6
    env: TOXENV=py36-2.0
  - python: 3.6
    env: TOXENV=py36-master
  allow_failures:
  - env: TOXENV=py35-master
  - env: TOXENV=py36-master
install:
- pip install tox coveralls
script:
- tox
after_success:
- if [ -f .coverage ]; then coveralls; fi
deploy:
  provider: pypi
  user: charettes
  distributions: sdist bdist_wheel
  password:
    secure: P3/8C47HKEp0iQohltLjgFIK9jPGt5ZTeyNU9ayRa9J3C3yWgKGLJrTYNsxhoTT60ZGkLuOnpNioIDwZ3oBjm6OrONYZZ7xwXPxPaHa/Uxu91Bqkb/0IMSXWAKnjGCvE8DtDaDkBEOd52wyVinrR2YLp11oJR/cVUikFVFHpSBrxEl5SxgaulL61R4EmEVT1Y7y+dO5XqOBygb8/n2HWaCXw8Jd/gxgG/vYQy5zOC8S1sbRU6zR4DnpkDTDbLskuIDL/MySh8k793S/vqRWXeXMw8XGu6b5E3z69Yr7fB1UqUkwbr/GWnfkkjUyRxP8q8xk/5pvoJ1IUpLM9yFQTrOHtoJfFGaFpb/7kwuWdePL2+y5Er3YqNInrTvDg0yEyvGMPBLxv7D+tfpnNYoCvwfvspFkXLwl1w3CbM57FkPezHboEY+CPHWis1UnDNk/0g4Yn72NFcMcBHmnGOARrBXWEx345IU7QqJsFucFoYFLZHnYayiGu2S43j9UNk+2/5PUBve6Z0yQ5VKq4Obme9DS3LN3pbcBAoSpo5zszs2/xUaRO9KZ/7a6GScWCB9tmwFvfmsg5XAQQLD+aC49ZTjeFa3DeY/zufnah69eZgGcM1OKS8jOQrv9h5nAFvExV+gldAtVbC5FgEYTPn06E3oB0J3IMBqXEts5f9xzQSj0=
  on:
    tags: true
    condition: "$TOXENV = py27-1.11"
